services:
  postgres:
    image: postgres:17.9-alpine
    container_name: ${CONTAINER_PREFIX:-restaurant}-postgres
    restart: always
    ports:
      - "${DATABASE_PORT:-5439}:5432"
    volumes:
      - restaurant_postgres_backend_data_prod:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
      POSTGRES_DB: ${DATABASE_NAME:-api}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DATABASE_USERNAME:-root} -d ${DATABASE_NAME:-api}',
        ]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - restaurant-backend-network

  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_PREFIX:-restaurant}-redis
    restart: always
    ports:
      - "${REDIS_PORT:-6382}:6379"
    volumes:
      - restaurant_redis_backend_data_prod:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - restaurant-backend-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: restaurant-backend:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_PREFIX:-restaurant}-api
    restart: always
    ports:
      - "${BACKEND_PORT:-6060}:3001"
    volumes:
      - restaurant_files_data_prod:/usr/src/app/files
    env_file:
      - .env
    environment:
      NODE_ENV: production
      API_PREFIX: backend
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_URL: postgresql://${DATABASE_USERNAME:-root}:${DATABASE_PASSWORD:-secret}@postgres:5432/${DATABASE_NAME:-api}?schema=public
      WORKER_HOST: redis://redis:6379/1
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - restaurant-backend-network

volumes:
  restaurant_postgres_backend_data_prod:
  restaurant_redis_backend_data_prod:
  restaurant_files_data_prod:

networks:
  restaurant-backend-network:
    driver: bridge
