ALTER TABLE "roles" DROP CONSTRAINT IF EXISTS "ck_roles__code";
ALTER TABLE "roles" ADD CONSTRAINT "ck_roles__code"
  CHECK ("code" IN ('OWNER_ADMIN', 'MANAGER', 'WAITER', 'CASHIER', 'STATION_OPERATOR', 'DISPATCHER'));